config/routes.rb
Rails.application.routes.draw do
  root 'twitodo#index'
  resources :twitodo, only: [:index, :show]
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  resources :groups
  get '/tweets', to: 'tweets#update'
  # resources :statuses, only: [:update]
  put '/statuses', to: 'statuses#update'
  # resources :statuses
  # put '/statuses', to: 'statuses#update'
  get '/user', to: 'users#destroy'
  get "/tweets/search" => 'tweets#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :tweets
  has_many :members
  has_many :users, through: :members
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :group, optional: true
end

app/models/twitter_api_search_client.rb
class TwitterApiSearchClient
  require "net/http"
  require "uri"
  require "json"
  # require 'faraday'
  # require 'faraday_middleware'

  TWITTER_SEARCH_ENDPOINT = "https://api.twitter.com/1.1/tweets/search/30day/prod.json"
  BEARER = ENV['BEARER']

  # def call(hashtag:, members:)
  #   params =  {
  #  "maxResults" => "10",
  #      "hashtag" => "#{hashtag}",
  #     }
  def call(hashtag:)
    params =  {"query" => "#{hashtag} lang:ja",
    "maxResults" => "100",}
    uri = URI.parse(TWITTER_SEARCH_ENDPOINT)

    request = Net::HTTP::Post.new(uri)
    request.content_type = "application/json"
    request["Authorization"] = BEARER
    request.body = params.to_json

    req_options = {
      use_ssl: uri.scheme == "https" 
     }

    response = Net::HTTP.start(uri.hostname, uri.port, req_options ) do |http|
      http.request(request)
    end

    JSON.parse(response.body)
    # a = JSON.parse(response.body)
    # a.select { |result| members.include?(result["results"]["user"]["screen_name"]) }
    # return response.where()
    # results['results']['user'][id_str]
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tweets
  has_many :members
  has_many :groups, through: :members
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update]

  def index
    @group = Group.all
  end

  def new
    @group = Group.new
    @group.members.build
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      render :index, notice: 'リストを作成しました'
    else
      render :new
    end

    # group = Group.create!(group_params)
    # group.user_ids.each do |user_id|
    #   user = User.find_by(user_id: user_id)
    #   group.members.create!(user: user)
    # end

  end

  def show
    @tweet = Tweet.all
    @new = Tweet.where(status: "1", group_identifier: @group.id)
    @wip = Tweet.where(status: "2", group_identifier: @group.id)
    @pending = Tweet.where(status: "3", group_identifier: @group.id)
    @completed = Tweet.where(status: "4", group_identifier: @group.id)
  end

  def edit
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_name: params["group"][:group_name], hashtag: params["group"][:hashtag])
      render :index, notice: 'リストを更新しました'
    else
      render :edit
    end
  end

  private

  def group_params
    params.require(:group).permit(:group_name, :hashtag, user_ids: [])
  end

  def set_group
    @group = Group.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    unless request.env['omniauth.auth'][:uid]
      flash[:danger] = '連携に失敗しました'
      redirect_to root_url
    end
    user_data = request.env['omniauth.auth']
    user = User.find_by(uid: user_data[:uid])
    if user
      log_in user
      flash[:success] = 'ログインしました'
      redirect_to root_url
    else
      new_user = User.new(
        uid: user_data[:uid],
        nickname: user_data[:info][:nickname],
        name: user_data[:info][:name],
        image: user_data[:info][:image],
      )
      if new_user.save
        log_in new_user
        flash[:success] = 'ユーザー登録成功'
      else
        flash[:danger] = '予期せぬエラーが発生しました'
      end
      redirect_to root_url
    end
  end


  def destroy
    log_out if logged_in?
    flash[:success] = 'ログアウトしました'
    redirect_to root_url
  end

end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController

  def update
    tweet = Tweet.find_by(tweet_id: params["tweet_id"])
    if tweet.update(status: params["status"])
      redirect_to controller: 'groups', action: 'show', id: tweet.group_identifier
    else
      redirect_to controller: 'groups', action: 'index', notice: "ステータスを変更出来ませんでした"
    end
  end

  private
  def status_params
    params.permit(:status, :tweet_id)
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def update
    group = Group.find(params[:format])

    hashtag = group.hashtag

    member = group.users.pluck(:nickname)
    result = TwitterApiSearchClient.new
    tweets = result.call(hashtag: "##{hashtag}")
    # tweets = result.call(hashtag: "##{hashtag}", members: member)

    tweets["results"].each do |tweet|
      Tweet.find_or_create_by!(tweet_id: tweet["id_str"], status: "1", group_identifier: group.id)
    end

    redirect_to controller: 'groups', action: 'show', id: group.id
  end

end

app/controllers/twitodo_controller.rb
class TwitodoController < ApplicationController
  # before_action :set_user

  def index
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def destroy
    @user = User.find(current_user.id)
    if @user.destroy
      redirect_to root_path
    else
      redirect_to root_path, notice: "削除出来ませんでした"
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:uid] = user.uid
  end

  def current_user
    if session[:uid]
      @current_user ||= User.find_by(uid: session[:uid])
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:uid)
    @current_user = nil
  end
  
end

app/helpers/twitodo_helper.rb
module TwitodoHelper
end

app/views/groups/edit.html.haml
= render 'shared/header'
= form_with model: @group, local: true, method: :put do |form|

  .form-container
    %form.col.s12
      .row
        .input-field.col.s12
          = form.text_field :group_name, class:"materialize-textarea", placeholder: @group.group_name, maxlength: "20"
          %label{for: "textarea1"} リストの名前
      .row
        .input-field.col.s12
          = form.text_field :hashtag, class:"materialize-textarea", placeholder: @group.hashtag, maxlength: "20"
          %label{for: "textarea1"} ハッシュタグ
    .divider
    .button-container
      %button.waves-effect.waves-light.btn-large
        = form.submit "Submit"

app/views/groups/index.html.haml
= render 'shared/header'
.group-container
  - current_user.groups.each do |g|
    .group-box
      .col.s12.m7
        .card.horizontal
          .card-stacked
            .card-content
              %label リストの名前/ハッシュタグ
              %p
                = g.group_name
              %p
                = g.hashtag
            .card-action
              %a
                = link_to "リストを見る", group_path(g)
              %a
                = link_to "リストを編集する", edit_group_path(g) 

app/views/groups/new.html.haml
= render 'shared/header'
= form_with model: @group, local: true do |form|

  .form-container
    %form.col.s12
      .row
        .input-field.col.s12
          = form.text_field :group_name, class:"materialize-textarea", placeholder: "リストの名前", maxlength: "20"
          %label{for: "textarea1"} リストの名前
      .row
        .input-field.col.s12
          = form.text_field :hashtag, class:"materialize-textarea", placeholder: "ハッシュタグ", maxlength: "20"
          %label{for: "textarea1"} ハッシュタグ(#は不要です)
    .divider
    .user-form-container
    .row
      #image.input-field.col.s12.user-add-form
        %label{for: "textarea1"} ユーザー(TwitterのID)開発中のため、このフォームは追加しないでください
        %br
        = form.hidden_field "user_ids[]", name: "group[user_ids][]", value: current_user.id
      %a.btn-floating.btn-small.waves-effect.waves-light.grey.user-add-btn ＋
    .divider
    .button-container
      %button.waves-effect.waves-light.btn-large
        = form.submit "Submit"

:javascript
  $(window).on('load', ()=> {
    const html = `
      <input name="group[user_ids][]" class="materialize-textarea" placeholder="ユーザー(TwitterのID)" maxlength="20" size="20" type="text" id="group_user_ids[]">
    `;
    $('.user-add-btn').on('click', function(e) {
      $('.user-add-form').append(html);
    });

  });

app/views/groups/show.html.haml
= render 'shared/header'
%link{href: "https://fonts.googleapis.com/icon?family=Material+Icons", rel: "stylesheet"}/

.row
  .col.s12
    %ul.tabs{style: " border-bottom: 1px dotted #bbb;"}
      %li
        .col.s2{style: "color: #ee6e73;"}
          Name:
          = @group.group_name
          %br
          Hashtag:
          = @group.hashtag
      %li.col.s2{style: "color: #ee6e73; padding-top: 0.5%; font-size: 16px;"}
        %i.material-icons{style: "padding-top: 1%"} autorenew
        = link_to 'Load new tweets', tweets_path(@group) , style: "color: #ee6e73;"
      %li.tab.col.s2{style: " border-left: 1px dotted #bbb;"}
        %a.active{href:"#new"} New
      %li.tab.col.s2
        %a.active{href: "#wip"} WIP
      %li.tab.col.s2
        %a{href: "#pending"} Pending
      %li.tab.col.s2
        %a{href: "#completed"} Completed
    #new.col.s12.tweet-container
      - @new.each do |tweet|
        = form_with url: statuses_path, method: :put, local: true do |f|
          .card.white.darken-1.tweet-container__box
            .card-content.white-text.tweet-container__box__tweet
              %blockquote.twitter-tweet
                %a{href: "https://twitter.com/a/status/#{tweet.tweet_id}?ref_src=twsrc%5Etfw"}
              %script{async: "", charset: "utf-8", src: "https://platform.twitter.com/widgets.js"}
              .card-action{style: "color: black;"}
                = f.select :status, [["Move this card to:", value = 1], ["WIP", value = 2],["PENDING", value = 3],["Completed", value = 4]], {}, {class: "browser-default"}
                = f.hidden_field :tweet_id, value: tweet.tweet_id
                %br
                %button.waves-effect.waves-light.btn-small
                  = f.submit "Submit"

    #wip.col.s12.tweet-container
      - @wip.each do |tweet|
        = form_with url: statuses_path, method: :put, local: true do |f|
          .card.white.darken-1.tweet-container__box
            .card-content.white-text.tweet-container__box__tweet
              %blockquote.twitter-tweet
                %a{href: "https://twitter.com/a/status/#{tweet.tweet_id}?ref_src=twsrc%5Etfw"}
              %script{async: "", charset: "utf-8", src: "https://platform.twitter.com/widgets.js"}
              .card-action{style: "color: black;"}
                = f.select :status, [["Move this card to:", value = 2], ["PENDING", value = 3],["Completed", value = 4]], {}, {class: "browser-default"}
                = f.hidden_field :tweet_id, value: tweet.tweet_id
                %br
                %button.waves-effect.waves-light.btn-small
                  = f.submit "Submit"

    #pending.col.s12.tweet-container
      - @pending.each do |tweet|
        = form_with url: statuses_path, method: :put, local: true do |f|
          .card.white.darken-1.tweet-container__box
            .card-content.white-text.tweet-container__box__tweet
              %blockquote.twitter-tweet
                %a{href: "https://twitter.com/a/status/#{tweet.tweet_id}?ref_src=twsrc%5Etfw"}
              %script{async: "", charset: "utf-8", src: "https://platform.twitter.com/widgets.js"}
              .card-action{style: "color: black;"}
                = f.select :status, [["Move this card to:", value = 3], ["WIP", value = 2],["Completed", value = 4]], {}, {class: "browser-default"}
                = f.hidden_field :tweet_id, value: tweet.tweet_id
                %br
                %button.waves-effect.waves-light.btn-small
                  = f.submit "Submit"

    #completed.col.s12.tweet-container
      - @completed.each do |tweet|
        = form_with url: statuses_path, method: :put, local: true do |f|
          .card.white.darken-1.tweet-container__box
            .card-content.white-text.tweet-container__box__tweet
              %blockquote.twitter-tweet
                %a{href: "https://twitter.com/a/status/#{tweet.tweet_id}?ref_src=twsrc%5Etfw"}
              %script{async: "", charset: "utf-8", src: "https://platform.twitter.com/widgets.js"}
              -# .card-action{style: "color: black;"}
              -#   = f.select :status, [["Move this card to:", ""], ["WIP", value = 2],["PENDING", value = 3],["Completed", value = 3]], {}, {class: "browser-default"}
              -#   = f.hidden_field :tweet_id, value: tweet.tweet_id
              -#   %br
              -#   %button.waves-effect.waves-light.btn-small
              -#     = f.submit "Submit"

:javascript
  $(document).ready(function(){
    $('.tabs').tabs();
  });

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitodo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_footer.html.haml
%footer.page-footer
  .container
    .row
      .col.l6.s1
        %h5.white-text Twitodo
        %p.grey-text.text-lighten-4 is an app allow you to manage tasks with mates.
      .col.l4.offset-l2.s1
        %h5.white-text Links
        %ul
          %li
            %a.grey-text.text-lighten-3{href: "https://github.com/akkt222/Twitodo"} Github
          %li
            %a.grey-text.text-lighten-3{href: "https://twitter.com/akkt222"} Twitter
          -# %li
          -#   %a.grey-text.text-lighten-3{href: "#!"} Link 3
          -# %li
          -#   %a.grey-text.text-lighten-3{href: "#!"} Link 4

app/views/shared/_header.html.haml
%ul#dropdown-menu.dropdown-content
  %li
    %a{href: "#!"}  ユーザー情報
  %li.divider
  %li
    = link_to '退会', user_path, method: :delete, data: { confirm: "退会しますか？" }
%nav
  .nav-wrapper
    %a.brand-logo{href: "#!"}
      =link_to "Twitodo", root_path
    - if logged_in?
      %ul.right.hide-on-med-and-down
        %li
          %a
            =link_to "リストの作成", new_group_path
        %li
          %a
            =link_to "リストの一覧", groups_path
        %li
          %a
            = link_to "ログアウト", logout_path, class: "ログアウト"
          -# - else
          -#   %a{href: "/auth/twitter"} ログイン
        %li
          %a.dropdown-trigger{"data-target" => "dropdown-menu", href: "#!"}
            メニュー
            -# %i.material-icons.right arrow_drop_down
    - else
      %ul.right.hide-on-med-and-down
        %li
          %a{href: "/auth/twitter"} Twitterアカウントでログイン

:javascript
  $(document).ready(function(){
    $('.dropdown-trigger').dropdown();
  });

app/views/twitodo/index.html.haml
= render 'shared/header'

.container-index
  .carousel-fixed-item.center
    = image_tag "top.png", size: "900x500"
    %p Links
    %a.btn.btn-large.waves-effect.orange.lighten-3.black-text.darken-text-2{href: "https://github.com/akkt222/Twitodo"} Github
    %a.btn.btn-large.waves-effect.orange.lighten-3.black-text.darken-text-2{href: "https://twitter.com/akkt222"} Twitter

  :javascript
    $(document).ready(function(){
     $('#demo-carousel-content').carousel();
      $('.carousel.carousel-slider').carousel({
        fullWidth: true,
        indicators: true
      });
    });

-# = render 'shared/footer'

app/views/twitodo/show.html.haml
= link_to "退会する" user_path(@user.id), method: :delete